name: mahlmann_app
description: Flutter Mehlmann app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.26+29
#version: 1.2.27+30

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0
  google_maps_flutter: ^2.0.3
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  uuid: ^3.0.4
  package_info: ^2.0.0
  intl: ^0.17.0
  intl_translation: ^0.17.10+1
  sqflite: ^2.0.0+3
  geolocator: ^7.0.3
  built_value: ^8.0.5
  path_provider: ^2.0.1
  maps_toolkit: ^1.1.0+2
  url_launcher: ^6.0.3
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.0
  action_cable_stream: ^0.0.3
  background_locator: ^1.5.0+1
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^3.1.1
#  firebase_crashlytics:
#    git:
#      url: git://github.com/FirebaseExtended/flutterfire.git
#      path: packages/firebase_crashlytics/firebase_crashlytics
#      ref: 200b8ca8f1c452e4249fb791e53cc55e786ac768

dependency_overrides:
  analyzer: ^1.5.0
  intl: ^0.17.0
  google_maps_flutter: ^2.0.3
  package_config: ^2.0.0
#  equitable: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  built_value_generator: ^8.0.4

  post_frame_image_builder:
    path: /Users/Admin/Development/flutter/my_plugins/post_frame_image_builder

  cluster_builder:
    path: /Users/Admin/Development/flutter/my_plugins/cluster_builder

  date_formatter_plugin:
    path: /Users/Admin/Development/flutter/my_plugins/date_formatter_plugin

  location_permissions:
    path: /Users/Admin/Development/flutter/plugins/flutter_permission_plugin/packages/location_permissions

#  background_locator:
#    path: /Users/Admin/Development/Android/custom/AgForce/background_locator

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    - assets/images/drop.png
    - assets/images/drop_ios.png
